backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/anime'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'My Anime List ID ( mal_id )', name: 'mal_id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label : 'Status', name: 'status', widget: 'string'}
      - { label: 'Anime Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }